### ISSUE TITLE
Failed to connect to server while loading singleplayer world

### ISSUE THREAD

**Issue by Plant544** [Disketaa/Minecraft-Enhanced#25]
![image](https://user-images.githubusercontent.com/105559395/168441308-0979b8bd-b64f-4f9a-8ac9-116e8dee1b0b.png)

**Comment by Disketaa** [comment]
Omg, thanks for the reporting it.
Everytime everything works perfectly until I upload a release on curseforge xd

Time to figure out!

**Comment by Disketaa** [comment]
Fixed in 2.3.4

**Comment by Plant544** [comment]
Thanks
